### ISSUE TITLE
ボスの溜めダメージ

### ISSUE THREAD

**Issue by Crocus7724** [Crocus7724/SengokuConquest#115]
ボスの溜めダメージが強すぎてサムライレベル6体力ほぼMAXでも即死したので1.5倍にしました。。。

**Comment by c0114573** [comment]
計算の仕方が間違ってましたすみません

ボスの溜めダメージは×1.4でお願いします

**Comment by Crocus7724** [comment]
承知致しました。

**Comment by Crocus7724** [comment]
対応いたしましたので閉じます。
