### ISSUE TITLE
AreaSceneの実装

### ISSUE THREAD

**Issue by Crocus7724** [Crocus7724/SengokuConquest#12]
AreaSceneを実装して下さい

- [x] AreaSceneのコンストラクタにAreaをつけて下さい
~~- [ ] 移動コマンドを実装して下さい~~→別Issue
  - ユーザからの入力を待ち、返ってきた値が正しい場合`Application.current.nexeScene(new AreaScene(Application.current.getMap.get(areaNumber)))`で次のエリアに遷移する処理を実装して下さい
~~- [ ] アイテムコマンドを実装して下さい~~→別Issue
  - `GameApplication.current.getMainCharacter().getItems()`でアイテムを取得して下さい。
    - [x] そこからHpItemとEpItemのインスタンスを判別する処理を加えて下さい
    - [x] Itemを使う場合、`item.useItem(GameApplication.current.getMainCharacter())`で回復します。
    - [ ] また、その場合使ったアイテムは消して下さい
~~- [x] 休憩コマンドを実装して下さい~~→別Issue
  - [x] ターン数を減らして下さい
  - [x] 体力を規定の量回復させる処理を入れて下さい

**Comment by C0114105emo** [comment]
遅れてすみません
休憩コマンドは実装できたと思うんですが・・・
アイテムコマンドの実装がいまいちです。移動コマンドの遷移もどうしたらよいのやら・・・といった感じです
getItems()でアイテムを取得した場合、リストの中のインデックスが返ってくるのか
それとも、リストの中のインデックスに紐づけられた要素そのものが返ってくるのか・・・・どっちでしょうか
とりあえずプルリクエストしてみます。誤った箇所ばかりだと思いますが、修正案をよろしくお願いします

**Comment by Crocus7724** [comment]
> getItems()でアイテムを取得した場合、リストの中のインデックスが返ってくるのか

これ、ちゃんとした実装まだなんですよね・・・すみません。おそらく取得した順にItemクラスが(HP・EPの区別なく)入っているのでforループで回してインスタンス比較してあったらフラグを立てるみたいな面倒くさい実装になりそうです。

また、現在の状態だと休憩コマンドを実行したらそのままSceneが終わり、ゲームが終了してしまうので再帰的な処理を挟まなければなりません。

ここいら辺の実装は重いので明日改めて相談させて下さい。

ここまでありがとうございました。助かりました!!

**Comment by Crocus7724** [comment]
コマンドなど、かなり複雑な実装になりそうなので一旦クラスを分けることにします。よってこれで本Issueは一旦完了とし、また別Issueでの作業とします。
