### ISSUE TITLE
ボスに挑む時の表示

### ISSUE THREAD

**Issue by c0114573** [Crocus7724/SengokuConquest#120]
一度もボス部屋に訪れていなくてレベル4以上の時
マップ探索してると突然ボス戦になるので

レベル4以上の時に移動した先がボスの部屋だった場合
「この先には織田信長がいます。織田信長に挑みますか？」
1：はい
2：いいえ
的なコマンドがほしい

「いいえ」　は移動しない(ターン数減らない)

**Comment by Crocus7724** [comment]
私が引き取ります

**Comment by Crocus7724** [comment]
対応致しました。問題なさそうならこのIssueを閉じちゃって下さい。
