### ISSUE TITLE
敵強さ変更

### ISSUE THREAD

**Issue by c0114573** [Crocus7724/SengokuConquest#123]
レベル1 Status(70,0,50,20);
レベル2 Status(80,0,55,25);
レベル3 Status(90,0,60,30);
レベル4 Status(150,1,66,35);
にしてみたらいい感じになったけどどうだろう

**Comment by Crocus7724** [comment]
設計者さんが言うことに間違いはない(確信)

**Comment by Crocus7724** [comment]
ミスってmasterに直接Pushしてしまったけどとりあえず対応致しました。

**Comment by Crocus7724** [comment]
#127 に合わせて
- Level1 攻撃力50→45
- レベル2 防御力25→20
- レベル4 攻撃力66→65

に変更したのですがこれで大丈夫ですか?

**Comment by c0114573** [comment]
50 25 66のままでいいです

**Comment by Crocus7724** [comment]
お、了解致しました。
