### ISSUE TITLE
リテラルを変数に&全体リファクタリング

### ISSUE THREAD

**Issue by Crocus7724** [Crocus7724/SengokuConquest#125]
致命的なバグも(今のところ)ないっぽいし、ここいら辺でリテラルを変数にして1ファイルにまとめる&&全体的なリファクタリングをします。

対象は全ファイルなのでもし少しでもコードを変更していた場合即コンフリクトする恐れがあります。
なのでその場合はプルリクエストを投げるか、1回Stashに変更を逃してマージ後Unstashして下さい。

また、作業が終了次第Tagをうってβリリースとしたいと思います。

このIssueはそのうち閉じます。

**Comment by c0114573** [comment]
了解しました

**Comment by Crocus7724** [comment]
# 残タスク

- [x] 文字列をStringsにまとめる
  - [x] character
  - [x] item
  - [x] map
  - [x] scene
    - [x] command
  - [x] utilities

- [x] 定数値をConstsにまとめる
  - [x] character
  - [x] item
  - [x] map
  - [x] scene
    - [x] command
  - [x] utilities

- [x] リファクタリング
  - [x] 不要なimport削除
  - [x] 変数・メソッド並び替え
  - [x] コードフォーマット

**Comment by Crocus7724** [comment]
マージされたので閉じます。
