### ISSUE TITLE
体力が0になってもゲームオーバーにならない

### ISSUE THREAD

**Issue by Crocus7724** [Crocus7724/SengokuConquest#128]
<img width="258" alt="screen shot 2016-12-05 at 22 30 30" src="https://cloud.githubusercontent.com/assets/11902894/20886663/863e0d5a-bb3a-11e6-9893-103b4b037e43.png">

まあ乱数ありだからなかなか再現しないだろうけど一応

**Comment by Crocus7724** [comment]
というか足軽難しすぎません?

**Comment by c0114573** [comment]
そのバグはコマンド入力後敵にダメージを与えたら死ねた

ボスは攻撃後力をためるようにするか考えてたけど難しすぎたか・・・
（そうするとレベル4侍と足軽は運が悪いと死ねるようになる）
ボスは特技を忍者は2回、他は特技を3回は使用しないと死ぬようにしてる

**Comment by Crocus7724** [comment]
> そのバグはコマンド入力後敵にダメージを与えたら死ねた

うーん謎い・・・

> ボスは特技を忍者は2回、他は特技を3回は使用しないと死ぬようにしてる

なるほど。手っ取り早いから侍しか使ってなかったのとバグチェックの目的で全国制覇してたので初めて知った・・・

**Comment by Crocus7724** [comment]
bool値がミスってただけでした。対応いたしましたので閉じます。
