### ISSUE TITLE
ストーリー　ルール内容の修正

### ISSUE THREAD

**Issue by c0114573** [Crocus7724/SengokuConquest#136]

**Comment by C0114544** [comment]
中間報告

メインストーリー
主人公は激怒した。必ず、かの邪智暴虐の魔王を除かなければならぬと決意した。主人公には政治がわからぬ。けれども邪悪に対しては、人一倍に敏感であった。
「呆れた魔王だ。生かして置けぬ。」
　主人公は捕縛され、「第六天魔王　織田信長」の前に引き出された。
「何をするつもりであったか。言え！」
「都を魔王の手から救うのだ。」
「だまれ、下賤の者。お前だって、磔になってから泣いて詫びたって聞かぬぞ。」
「自惚れているがよい。ただ、私に情をかけたいつもりなら、処刑までに25ターンの限を与えて下さい。必ず、ここへ帰って来ます。」
　「ばかな。逃がした小鳥が帰って来るというのか。」
「そうです。帰って来るのです。私は約束を守ります。この都に竹馬の友がいます。人質としてここに置いて行こう。私が帰って来なかったら、あの友を殺して下さい。」
「願いを、聞いた。その身代りを呼ぶがよい。ちょっと遅れて来るがいい。おまえの罪は、永遠にゆるしてやろう。」
「何をおっしゃる。」主人公は地団駄踏んだ。ものも言いたくなくなった。
　竹馬の友は王城に召された。主人公は、友に一切の事情を語った。友は無言で首肯き、主人公をひしと抱きしめた。友と友の間は、それでよかった。主人公は、すぐに出発した。
　初夏、満天の星である。

勝利
「待て。その人を殺してはならぬ。主人公が帰って来た。約束のとおり、いま、帰って来た。殺されるのは、私だ。彼を人質にした私は、ここにいる！」
と、かすれた声で叫びながら、磔台に釣り上げられてゆく友の両足に齧りついた。
友の縄は、ほどかれたのである。
「友よ。私を殴れ。君が若し私を殴ってくれなかったら、私は君と抱擁する資格さえ無いのだ。殴れ。」
友は、すべてを察した様子で首肯き、刑場一杯に鳴り響くほど音高く殴った。殴ってから優しく微笑み、
「友よ、私を殴れ。同じ位私の頬を殴れ。君が私を殴ってくれなければ、私は君と抱擁できない。」
　主人公は腕に唸りをつけて殴った。
「「ありがとう、友よ。」」
二人同時に言い、ひしと抱き合い、それから嬉し泣きにおいおい声を放って泣いた。


ターン敗北
　流石に疲労し、がくりと膝を折った。立ち上る事が出来ぬのだ。ああ、ここまで走破して来た主人公よ。真の勇者よ。今、ここで、動けなくなるとは情無い。
　全身萎えて、もはや芋虫ほどにも前進かなわぬ。私は、この大事な時に、精も根も尽きたのだ。友よ、許してくれ。私たちは、本当に佳い友と友であったのだ。
――私は、死ぬよりつらい。私は、永遠に裏切り者だ。

戦闘敗北
　呼吸も出来ず、二度、三度、口から血が噴き出た。立ち上る事が出来ぬのだ。ああ、ここまで突破して来た主人公よ。真の勇者よ。今、ここで、動けなくなるとは情無い。
　全身傷つき、もはや蟻一匹ほどにも戦うことができぬ。私は、この大事な時に、血も魂も尽きたのだ。友よ、許してくれ。私たちは、本当に佳い友と友であったのだ。
――私は、死ぬよりつらい。私は、永遠に裏切り者だ。

**Comment by Crocus7724** [comment]
個人的意見:

> 勝利

~~もろメロスやん~~
もうちょっと第六天魔王さんのことにも触れてあげて

> 流石に疲労し

流石はいらない気がする・・・

> 情無い

読めなくはないけどたぶん情けないのほうが直感的

> ――私は、死ぬよりつらい。私は、永遠に裏切り者だ。

悲壮感半端なくないですかw
一応コンティニューできるようにする予定なのでもうちょっと次に繋がる希望的なのが欲しいです

**Comment by Crocus7724** [comment]
本件実装したので閉じます
