### ISSUE TITLE
EndScene実装

### ISSUE THREAD

**Issue by Crocus7724** [Crocus7724/SengokuConquest#14]
EndSceneを実装して下さい。

- [x] startメソッドに実装して下さい。(end,restartは使わない想定)
- [x] 文字出力はGameEngineクラスを使って下さい。
- [x] 終了条件によってEndを分岐して下さい
  - [x] ターンがなくて終了
    - これはGameApplicationクラスのgetTurn()で分岐できるはずです
  - [x] 体力がなくて終了
    - これはgetMainCharacter().getStatus().getCurrentHpで分岐できるはずです
  - [x] ボス勝利
    - これは上記以外のときで分岐できるはずです

**Comment by C0114544** [comment]
getTurn()確認しようとしてandroid studioみたら、更新できないんだけどこれどういうこと？

**Comment by C0114544** [comment]
試しに作ったのぷるりく送ったから見てみて

**Comment by Crocus7724** [comment]
すみません、一昨日昨日と忙しくてｷﾞｯﾊﾌﾞ見てる時間ありませんでした。

getTurn()(とgetMainCharacter())ができない件ですが、`GameApplication.current.`を前に付けることで取得できるはずです。

よろしくお願いいたします。

**Comment by C0114544** [comment]
後で修正します

**Comment by Crocus7724** [comment]
これでOKです!閉じます。
