### ISSUE TITLE
タイトル作成

### ISSUE THREAD

**Issue by Crocus7724** [Crocus7724/SengokuConquest#141]
#133 対応

現在、タイトルが表示されません。

なのでタイトル表示を入れて下さい。

タイトルという都合上、AAがおすすめです

**Comment by C0114544** [comment]
lllllllllll,,　　　　　　　　　　　 　　 　　　　　 　lll
　ll,,,,　'''' 　 ,,,,,,,,, 　,,,,,,,,,,,,, 　 ,,,,,,,,,,,,,　,,,,,,,,,,　 llll　,,,,,,　,,, 　 ,,,
　'''''''lllll,,　lllll,,,,lllll　llll''　lllll　llll　llll　,lll''　'llll, llll,,llll'' 　llll 　 lll
'llll,, 　,,llll　lll,,　,,,,,　llll 　lllll　lllllllll''　 lll,,　,llll' llll'''''lll,　llll,　,,llll
　''''''''''''' 　 '''''''''''　''''' 　'''''　lll''''''llll 　''''''''''　 ''' 　 ''''　'''''''''''''
　　 　　　 　　　　　　 　　 　''''''''''''
　　　 　 　　 　　　,,,,,,,,,,,
　 　　　　　　　　llll'''　''llll,　　　　　　　　　　　　　　　　　　　　　　 　　　　　　　 llll
　 　　 　 　　　 ,llll　　　'''' 　,llll''llll,,　llllll'''llll,　,llll'''llllll　lll 　 llll　,llll'''llll,　,,lll''''lll, '''llll'''''
　　 　　　　　　 'llll, 　　,llll　llll 　 llll　lll 　 lll　llll 　 lll　llll　 lllll　lll'''''''lll'　''llllllll,, 　lll
　　　　　　　　 　''lllll,,,,llll''　 'llll,,,llll'　llll 　 llll　'llll,,,llllll　lll,,,,llllll　''llll,,,llll'　'lll,,,,,lll'　 llll,,,,
　　 　 　　　　　 　 　　　 　 　 　　　　　　　　 　　 lll

**Comment by Crocus7724** [comment]
⭐
これでオッケーぽいですね。

ただ、これをそのまま書くか、それとも周りを何かで囲うかはちょっと議論の余地がありそうです

**Comment by C0114544** [comment]
'''
____                         _             ____                                  _   
/ ___|  ___ _ __   __ _  ___ | | ___   _   / ___|___  _ __   __ _ _   _  ___  ___| |_ 
\___ \ / _ \ '_ \ / _` |/ _ \| |/ / | | | | |   / _ \| '_ \ / _` | | | |/ _ \/ __| __|
 ___) |  __/ | | | (_| | (_) |   <| |_| | | |__| (_) | | | | (_| | |_| |  __/\__ \ |_ 
|____/ \___|_| |_|\__, |\___/|_|\_\\__,_|  \____\___/|_| |_|\__, |\__,_|\___||___/\__|
                  |___/                                        |_|         

'''

**Comment by Crocus7724** [comment]
#145 に続く
