### ISSUE TITLE
コンソールで文字化け

### ISSUE THREAD

**Issue by Crocus7724** [Crocus7724/SengokuConquest#144]
Windowsのコンソールで実行すると文字化けする

## 原因
Formmterでformatしてるところだけ文字化けしている

**Comment by Crocus7724** [comment]
@C0114105emo これを確認していただいてもよろしいですか?
[SengokuConquest.zip](https://github.com/Crocus7724/SengokuConquest/files/656463/SengokuConquest.zip)

**Comment by Crocus7724** [comment]
これの確認をお願いします
[SengokuConquest.zip](https://github.com/Crocus7724/SengokuConquest/files/656532/SengokuConquest.zip)

**Comment by Crocus7724** [comment]
これの確認をお願いしますパート3
[SengokuConquest.zip](https://github.com/Crocus7724/SengokuConquest/files/656541/SengokuConquest.zip)

**Comment by Crocus7724** [comment]
これの確認をお願い致しますパート4
[SengokuConquest.zip](https://github.com/Crocus7724/SengokuConquest/files/656568/SengokuConquest.zip)

**Comment by Crocus7724** [comment]
これの確認をお願い致しますパート5
[SengokuConquest.zip](https://github.com/Crocus7724/SengokuConquest/files/656582/SengokuConquest.zip)

**Comment by Crocus7724** [comment]
これの確認をお願い致しますパート6
[SengokuConquest.zip](https://github.com/Crocus7724/SengokuConquest/files/656584/SengokuConquest.zip)

**Comment by Crocus7724** [comment]
これの確認をお願い致しますパート7
[SengokuConquest.zip](https://github.com/Crocus7724/SengokuConquest/files/656590/SengokuConquest.zip)

**Comment by Crocus7724** [comment]
これの確認をお願い致しますパート8
[SengokuConquest.zip](https://github.com/Crocus7724/SengokuConquest/files/656592/SengokuConquest.zip)

**Comment by Crocus7724** [comment]
これの確認をお願い致しますパート9
[SengokuConquest.zip](https://github.com/Crocus7724/SengokuConquest/files/656593/SengokuConquest.zip)

**Comment by Crocus7724** [comment]
これが最後と信じて
[SengokuConquest.zip](https://github.com/Crocus7724/SengokuConquest/files/656601/SengokuConquest.zip)

**Comment by Crocus7724** [comment]
最終回
[SengokuConquest.zip](https://github.com/Crocus7724/SengokuConquest/files/656610/SengokuConquest.zip)

**Comment by C0114105emo** [comment]
おめでとう

**Comment by Crocus7724** [comment]
@c0114573 ありがとう

**Comment by Crocus7724** [comment]
本件対応いたしましたので閉じます
