### ISSUE TITLE
タイトル実装

### ISSUE THREAD

**Issue by Crocus7724** [Crocus7724/SengokuConquest#145]
#141 で作ったタイトルをプログラムに実装して下さい。

StringsクラスにTITLEフィールドをほかと同じように`public static final Stiring`で宣言して下さい。
そして、GameApplicationのコンストラクタを作り、そのなかで`GameEngine.current.showMessage(Strings.TITLE)`を実装して下さい。

あと、文字が崩れないかの確認をよろしくお願いいたします。

**Comment by C0114544** [comment]
**
  _____                        _             _____                                  _   
 / ____|                      | |           / ____|                                | |  
| (___   ___ _ __   __ _  ___ | | ___   _  | |     ___  _ __   __ _ _   _  ___  ___| |_ 
 \___ \ / _ \ '_ \ / _` |/ _ \| |/ / | | | | |    / _ \| '_ \ / _` | | | |/ _ \/ __| __|
 ____) |  __/ | | | (_| | (_) |   <| |_| | | |___| (_) | | | | (_| | |_| |  __/\__ \ |_ 
|_____/ \___|_| |_|\__, |\___/|_|\_\\__,_|  \_____\___/|_| |_|\__, |\__,_|\___||___/\__|
                    __/ |                                        | |                    
                   |___/                                         |_|                    

**

**Comment by C0114544** [comment]
+-+-+-+-+-+-+-+ +-+-+-+-+-+-+-+-+
|S|e|n|g|o|k|u| |C|o|n|q|u|e|s|t|
+-+-+-+-+-+-+-+ +-+-+-+-+-+-+-+-+

**Comment by C0114544** [comment]
バックスラッシュが¥になってしまうのとかなり崩れてしまうので下のタイトルを考えてみました。

+-+-+-+-+-+-+-+ +-+-+-+-+-+-+-+-+
|S|e|n|g|o|k|u| |C|o|n|q|u|e|s|t|
+-+-+-+-+-+-+-+ +-+-+-+-+-+-+-+-+

**Comment by C0114544** [comment]
タイトル案2
```
 ___                    _          ___                              _   
/ __| ___ _ _  __ _ ___| |___  _  / __|  __ _ _   __  __ __ ___ __ | |_ 
|__ |/ -_) ' |/ _` / _ | / / || || (__ / _ | ' |/ _` || || / -_|_-<  _|
|___/|___|_||_|__, |___/_|_||_,_||____|___/_||_| __, ||_,_|___/ __/|__|
              |___/                                |_|                
```

**Comment by Crocus7724** [comment]
本件対応しましたので閉じます
