### ISSUE TITLE
コマンドのクラス分割

### ISSUE THREAD

**Issue by Crocus7724** [Crocus7724/SengokuConquest#30]
## 背景
コマンドがかなり複雑でちょっと処理が汚くなりそうだからクラスを分けちゃいましょう。

## 作るべきクラス
- [x] マップでのコマンド
  - [x] 移動
  - [x] アイテム使用
    - [x] HPアイテム
    - [x] EPアイテム
  - [x] 休憩

- [x] 戦闘でのコマンド
  - [x] 通常攻撃
  - [x] 特殊攻撃
  - [x] 逃げる

**Comment by C0114105emo** [comment]
ＥＸＰ増えてもlvup しなかったです

**Comment by C0114105emo** [comment]
levelup計算ですがgetlevel()でlevel取得して、そこからレベルの計算はしているけど、levelの計算し終わった値がどこにも代入されてないかもしれない

**Comment by C0114105emo** [comment]
レベルは変動してないですが、ステータスは経験値が1増えるごとに経験値がＨＰでいうと5づつ増えてるレベルあがってないのにステータスは最強になってしまっている

**Comment by C0114105emo** [comment]
敵キャラはとくにバグはありません

**Comment by C0114105emo** [comment]
ref #51

**Comment by Crocus7724** [comment]
とりあえずこれで大丈夫です。閉じます
