### ISSUE TITLE
Mapテスト

### ISSUE THREAD

**Issue by Crocus7724** [Crocus7724/SengokuConquest#54]
#50 関連

マップのテストを実施します。

基本的には #51 のマップバージョンを実施して下さい

**Comment by Crocus7724** [comment]
- Mapの1に某さんがくるはずですが、2に入っています。

**Comment by C0114544** [comment]
-アイテムの名前が表示されない。
-アイテムが合計で1つしか出てこない(マップの3地方(北,中央,南)にのみ出現するわけではない)。
-エリア8の西が12になっている。(本当は13でなければならない)
-エリア10の北が10になっている。(本当は9でなければならない)
-エリア11の北が8になっている。(本当は13でなければならない)
-エリア18の西が18になっている。(本当は20でなければならない)
-エリア19の西が19になっている。(本当は21でなければならない)
-敵の位置が固定。
-敵ごとのレベルの設定が間違っている。(正しいレベルはドライブの詳細設計に追記した。)

**Comment by Crocus7724** [comment]
とりあえずこれで閉じます
