### ISSUE TITLE
エリアが遷移したときにどのように表示するべきか

### ISSUE THREAD

**Issue by Crocus7724** [Crocus7724/SengokuConquest#68]
```
現在位置 : 1
コマンドを入力して下さい
1 : 移動
2 : 休憩
3 : アイテム使用
1
1:南
1
現在位置 : 2
コマンドを入力して下さい
1 : 移動
2 : 休憩
3 : アイテム使用
```

現在上記のように表示しています。
これをどのように表示すべきか

**Comment by Crocus7724** [comment]
例えば:
現在位置の下にターン数追加
```
現在位置 : 1
ターン数:15
コマンドを入力して下さい
1 : 移動
2 : 休憩
3 : アイテム使用
1
1:南
1
現在位置 : 2
ターン数:14
コマンドを入力して下さい
1 : 移動
2 : 休憩
3 : アイテム使用
```

**Comment by C0114105emo** [comment]
現在位置を県名ってどうっすか
ターン数はそれいいです賛成

**Comment by Crocus7724** [comment]
1マス:
```
--------
|           |
|    16   |
|           |
--------
```
のように表示

**Comment by C0114544** [comment]
┌─┬─┬─┬─┬─┬─┬─┬─┐
│   │   │   │   │   │   │   │1 │
├─┼─┼─┼─┼─┼─┼─┼─┤
│ ...│ ...│ ...│ ...│ ...│ ...│ ...│ ...│
├─┼─┼─┼─┼─┼─┼─┼─┤
│ ...│ ...│ ...│ ...│ ...│ ...│ ...│ ...│
├─┼─┼─┼─┼─┼─┼─┼─┤
│ ...│ ...│ ...│○│●│ ...│ ...│ ...│
├─┼─┼─┼─┼─┼─┼─┼─┤
│ ...│ ...│ ...│●│○│ ...│ ...│ ...│
├─┼─┼─┼─┼─┼─┼─┼─┤
│ ...│ ...│ ...│ ...│ ...│ ...│ ...│ ...│
├─┼─┼─┼─┼─┼─┼─┼─┤
│ ...│ ...│ ...│ ...│ ...│ ...│ ...│ ...│
├─┼─┼─┼─┼─┼─┼─┼─┤
│ ...│ ...│ ...│ ...│ ...│ ...│ ...│ ...│
└─┴─┴─┴─┴─┴─┴─┴─┘

**Comment by Crocus7724** [comment]
決定:マップ作る

**Comment by C0114544** [comment]
試し
┌─┬─┬─┬─┬─┬─┬─┬─┐
│   │    │   │   │   │   │   │1 │
├─┼─┼─┼─┼─┼─┼─┼─┤
│ ...│ ...│ ...│ ...│ ...│ ...│ 5│ 2│
├─┼─┼─┼─┼─┼─┼─┼─┤
│ ...│ 24│ 20│ 18│ 14│ 12│ 6│3│
├─┼─┼─┼─┼─┼─┼─┼─┤
│ ...│ 25│ 21│19│15│ 13│ 8│ 4│
├─┼─┼─┼─┼─┼─┼─┼─┤
│ ...│ ...│ 23│22│16│ 11│ 9│ 7│
├─┼─┼─┼─┼─┼─┼─┼─┤
│ ...│ ...│ ...│ ...│ 17│ ...│ 10│ ...│
└─┴─┴─┴─┴─┴─┴─┴─┘

**Comment by C0114105emo** [comment]
アイテム使用
-------------
プレイヤーの行動⇒

**Comment by C0114544** [comment]
┌─┬─┬─┬─┬─┬─┬─┬─┐
│    │    │    │    │    │    │ 1 │
├─┼─┼─┼─┼─┼─┼─┼─┤
│    │    │    │    │    │ 5 │ 2 │
├─┼─┼─┼─┼─┼─┼─┼─┤
│ 24 │ 20 │ 18 │ 14 │ 12 │ 6 │ 3 │
├─┼─┼─┼─┼─┼─┼─┼─┤
│ 25 │ 21 │ 19 │ 15 │ 13 │ 8 │ 4 │
├─┼─┼─┼─┼─┼─┼─┼─┤
│   │ 23 │ 22 │ 16 │ 11 │ 9 │ 7 │
├─┼─┼─┼─┼─┼─┼─┼─┤
│   │    │    │ 17 │   │ 10 │   │
└─┴─┴─┴─┴─┴─┴─┴─┘

**Comment by C0114105emo** [comment]
```
-----------------
現在位置 : 1
ターン数:15
コマンドを入力して下さい
1 : 移動
2 : 休憩
3 : アイテム使用
------------------
コマンド⇒1
1:南
1
現在位置 : 2
ターン数:14
コマンドを入力して下さい
1 : 移動
2 : 休憩
3 : アイテム使用
アイテム使用
----------------------------------
```

**Comment by Crocus7724** [comment]
閉じます
