### ISSUE TITLE
バトル時にどのように表示すべきか

### ISSUE THREAD

**Issue by Crocus7724** [Crocus7724/SengokuConquest#70]
現在:

```
SAMURAIの攻撃!
32のダメージ!
蠣崎慶広の攻撃!
14のダメージ!
------STATUS------
| NAME  SAMURAI  |
| LEVEL 2        |
| EXP   2        |
| HP    35 / 110 |
| EP    3 / 3    |
| ATK   52       |
| DEF   32       |
------------------
コマンドを選択して下さい
1 : 通常攻撃
2 : 特殊攻撃
3 : 逃走
1
SAMURAIの攻撃!
32のダメージ!
蠣崎慶広を倒した!!
経験値を1手に入れた!
```

**Comment by C0114544** [comment]
戦闘のコマンド選択時に不正な値を入力するとバグって落ちる

**Comment by C0114544** [comment]
SAMURAI の 攻撃!
32 の ダメージ!

蠣崎慶広 の 攻撃!
14 の ダメージ!

  ------STATUS------
| NAME  SAMURAI  |
| LEVEL   2                |
| EXP      2                |
| HP       35 / 110     |
| EP        3 / 3           |
| ATK      52              |
| DEF     32               |
  ------------------

コマンドを選択して下さい
1 : 通常攻撃
2 : 特殊攻撃
3 : 逃走

1

SAMURAI の 攻撃!
32 の ダメージ!

蠣崎慶広 を 倒した!!

経験値 を 1 手に入れた!

**Comment by c0114573** [comment]
敵のレベル表示
engine.showMessage(enemy.getName() + " lv"+enemy.getLevel() + "が現れた!!");

**Comment by c0114573** [comment]
通常攻撃使用時
> 1

SAMURAIの攻撃!
伊達輝宗に31のダメージを与えた!
伊達輝宗の攻撃!
22のダメージを受けた!

特殊攻撃使用時
> 2

SAMURAIは居合切りを使った!!
伊達輝宗に54のダメージを与えた!!
伊達輝宗の攻撃!
22のダメージを受けた!

**Comment by Crocus7724** [comment]
> 伊達輝宗に54のダメージを与えた!!
> 22のダメージを受けた!

→○○は○のダメージ!!

にさせて下さい・・・(統一する都合上そちらのほうが楽)

**Comment by Crocus7724** [comment]
とりあえず閉じます。問題があればまたOpenにして下さい
