### ISSUE TITLE
ルールを表示時に表示するテキスト作成

### ISSUE THREAD

**Issue by Crocus7724** [Crocus7724/SengokuConquest#73]
ストーリーを作成して下さい

考えたストーリーをこのIssueに上げて下さい。

**Comment by C0114544** [comment]
主人公は激怒した。必ず、かの邪智暴虐の魔王を除かなければならぬと決意した。主人公には政治がわからぬ。けれども邪悪に対しては、人一倍に敏感であった。
　主人公は内気な妹と二人暮しだ。この妹は結婚式も間近なのである。それゆえ、今日未明主人公は村を出発し、花嫁の衣裳やら祝宴の御馳走やらを買いに3マスはなれた此の京の都にやって来た。

　主人公には竹馬の友があった。今は此の都に住んでいる。その友を、訪ねてみるつもりなのだ。歩いているうちに主人公は、都の様子を怪しく思った。もう既に日も落ちて、暗いのは当りまえだが、夜のせいばかりでは無く、都全体がやけに寂しい。暢気な主人公も、段々と不安になって来た。

　路で逢った老爺をつかまえて、何かあったのか、前に都に来たときは、夜でも賑やかであった筈だが、主人公は語勢を強くして質問した。老爺は、わずか答えた。
「魔王様は、人を殺します。」
「なぜ殺すのだ。」
「悪心を抱いている、というのですが、誰も悪心を持っては居りませぬ。」
「たくさんの人を殺したのか。」
「はい、はじめは魔王様の妹婿さまを。それから、御自身のお世嗣、妹さまと妹さまの御子さま、皇后さまを。それから、賢臣の明智光秀様を。」
「驚いた。魔王は乱心か。」
「いいえ、乱心ではございませぬ。人を信ずる事が出来ぬ、と言うのです。今日は、六人殺されました。」聞いて、主人公は激怒した。
「呆れた魔王だ。生かして置けぬ。」

　主人公は、単純な男であった。のそのそ魔王城にはいって行った。たちまち巡邏の警吏に捕縛され、主人公は、魔王の前に引き出された。
「何をするつもりであったか。言え！」
「第六天魔王　織田信長」は静かに、けれども威厳を以て問いつめた。
「都を魔王の手から救うのだ。」と主人公は悪びれずに答えた。
「お前がか？」魔王は、憫笑した。「仕方の無いやつじゃ。おまえには、わしの孤独がわからぬ。」
主人公は、いきり立って反駁した。「言うな！人の心を疑うのは、最も恥ずべき悪徳だ。」
「疑うのが、正当の心構えなのだ。人の心は、あてにならない。信じては、ならぬ。」
魔王は落着いて呟き、ほっと溜息をついた。「わしだって、平和を望んでいるのだが。」
「なんの為の平和だ。」今度は主人公が嘲笑した。
「罪の無い人を殺して、何が平和だ。」
「だまれ、下賤の者。口では、どんな清らかな事でも言える。お前だって、磔になってから、泣いて詫びたって聞かぬぞ。」
「ああ、魔王は悧巧だ。自惚れているがよい。私は、ちゃんと死ぬる覚悟で居るのに。命乞いなど決してしない。ただ、――」主人公は瞬時ためらい、「ただ、私に情をかけたいつもりなら、処刑までに20ターンの限を与えて下さい。たった一人の妹に、亭主を持たせてやりたいのです。必ず、ここへ帰って来ます。」

　「ばかな。」と魔王は、嗄れた声で低く笑った。「とんでもない嘘を言うわい。逃がした小鳥が帰って来るというのか。」
「そうです。帰って来るのです。私は約束を守ります。私を、三日間だけ許して下さい。そんなに私を信じられないならば、よろしい、この市に竹馬の友がいます。私の無二の友人だ。人質としてここに置いて行こう。私が20ターン目の日暮まで、ここに帰って来なかったら、あの友を絞め殺して下さい。」

　それを聞いて魔王は、そっと北叟笑んだ。生意気なことを言うわい。どうせ帰って来ないにきまっている。騙された振りして、放してやるのも面白い。そうして身代りの友を、20ターン目に殺してやるのも気味がいい。
「願いを、聞いた。その身代りを呼ぶがよい。20ターン目の日没までに帰って来い。遅れたら、その身代りを、きっと殺すぞ。ちょっと遅れて来るがいい。おまえの罪は、永遠にゆるしてやろうぞ。」
「何をおっしゃる。」
「はは。命が大事だったら、遅れて来い。お前の心は、わかっているぞ。」
主人公は地団駄踏んだ。ものも言いたくなくなった。

　竹馬の友は、深夜、王城に召された。「第六天魔王　織田信長」の面前で、友と友は、二年ぶりで相逢うた。主人公は、友に一切の事情を語った。友は無言で首肯き、主人公をひしと抱きしめた。友と友の間は、それでよかった。竹馬の友は、縄打たれた。主人公は、すぐに出発した。初夏、満天の星である。

**Comment by Crocus7724** [comment]
@C0114544 リジェクト

**Comment by Crocus7724** [comment]
@C0114544 ルールを書いて下さい

**Comment by c0114573** [comment]
ルール
友のために織田信長を倒そう
日本を旅して大名を倒しレベルを上げよう
レベル4になると織田信長に挑める
ターンが0になると敗北

コマンド説明
移動コマンド
　移動　1ターン消費しマップの隣り合うマス東西南北に1マス移動
　休憩　1ターン消費しHP30回復
　アイテム使用　アイテムを使用

戦闘コマンド
　通常攻撃　
　特殊攻撃　EPを1消費する攻撃
　逃走　　　1ターン消費し1マス戻る(織田信長以外は必ず逃げられる)

アイテム説明
　握り飯　HP50回復
　秘薬　　EP3回復
　*回復は最大値を超えることはない

職業説明
　侍　level1 HP105 ATK50 DEF30 EP3
　　　特技：居合切り
　　　通常攻撃の1.45倍ダメージ

　忍者　level1 HP85 ATK60 DEF30 EP2
　　　特技：変わり身の術
　　　通常攻撃の0.8倍ダメージ、次の攻撃のダメージを受けない

　足軽　level1 HP110 ATK40 DEF45 EP4
　　　特技：一揆
　　　通常攻撃ダメージ、次の敵攻撃時反撃(自分が受けたダメージを与える)

　虚無僧　level1 HP90 ATK45 DEF30 EP4
　　　特技：吸魂
　　　通常攻撃の1.2倍ダメージ、減らした体力分回復

**Comment by Crocus7724** [comment]
とりあえずこれで実装しましょう。
