### ISSUE TITLE
コマンド選択バグ報告

### ISSUE THREAD

**Issue by C0114544** [Crocus7724/SengokuConquest#87]
```
徳川家康を倒した!!
経験値を2手に入れた!
レベルが上った!!
-----STATUS------
| NAME  KOMUSOU |
| LEVEL 2       |
| EXP   2       |
| HP    19 / 95 |
| EP    4 / 4   |
| ATK   47      |
| DEF   32      |
-----------------
現在位置 : 10
ターン数 : 24
コマンドを入力して下さい
1 : 移動
2 : 休憩
3 : ステータスを表示する
4 : アイテム使用
> 4

値が不正です
コマンドを入力して下さい
1 : 移動
2 : 休憩
3 : ステータスを表示する
4 : アイテム使用
> 4

使用するアイテムを選択してください。
1 : 握り飯:1個
2 : 使用しない
> 
```

**Comment by C0114544** [comment]
虚無僧の特技で体力が回復しない。
-----STATUS------
| NAME  KOMUSOU |
| LEVEL 2       |
| EXP   2       |
| HP    69 / 95 |
| EP    4 / 4   |
| ATK   47      |
| DEF   32      |
-----------------
敵体力 : [====================]
コマンドを選択して下さい
1 : 通常攻撃
2 : 特殊攻撃
3 : 逃走
> 2

吸魂を使った!!
北条氏政に35のダメージを与えた
KOMUSOUは35回復した!!
北条氏政の攻撃!
12のダメージ!
-----STATUS------
| NAME  KOMUSOU |
| LEVEL 2       |
| EXP   2       |
| HP    23 / 95 |
| EP    3 / 4   |
| ATK   47      |
| DEF   32      |
-----------------
敵体力 : [============        ]
コマンドを選択して下さい

**Comment by Crocus7724** [comment]
うーん、再現しない・・・

様子見ですね・・・

**Comment by Crocus7724** [comment]
何回かテストプレイして全く一度も再現しなかったのでとりあえず`wont fix`とします。
また問題が起こったらOpenして下さい。
