### ISSUE TITLE
不思議なチカラ

### ISSUE THREAD

**Issue by c0114573** [Crocus7724/SengokuConquest#95]
不思議なチカラで阻まれたときはターンが減らないようにしたい

現在位置 : 14
ターン数 : 1
不思議なチカラで阻まれた!!
現在位置 : 12
ターン数 : 1
コマンドを入力して下さい
1 : 移動
2 : 休憩
3 : ステータスを表示する
4 : アイテム使用
> 1

1:東
2:南
3:西
> 3

行動ターンがなくなってしまった！！
GAME OVER...

**Comment by Crocus7724** [comment]
対応致しました。
