### ISSUE TITLE
虚無僧レベル上がらないバグ

### ISSUE THREAD

**Issue by C0114544** [Crocus7724/SengokuConquest#96]
```
-----STATUS------
| NAME  KOMUSOU |
| LEVEL 2       |
| EXP   3       |
| HP    55 / 95 |
| EP    2 / 2   |
| ATK   47      |
| DEF   32      |
-----------------
敵体力 : [=====               ]
コマンドを選択して下さい
1 : 通常攻撃
2 : 特殊攻撃
3 : 逃走
> 1

KOMUSOUの攻撃!
26のダメージ!
長宗我部元親を倒した!!
経験値を1手に入れた!
現在位置 : 22
ターン数 : 10
コマンドを入力して下さい
1 : 移動
2 : 休憩
3 : ステータスを表示する
4 : アイテム使用
> 3

-----STATUS------
| NAME  KOMUSOU |
| LEVEL 2       |
| EXP   1       |
| HP    55 / 95 |
| EP    2 / 2   |
| ATK   47      |
| DEF   32      |
-----------------
現在位置 : 22
ターン数 : 10
コマンドを入力して下さい
1 : 移動
2 : 休憩
3 : ステータスを表示する
4 : アイテム使用
> 
```

虚無僧のレベルが上がらない。

**Comment by c0114573** [comment]
MainCharacterクラス
 public void setExp(int exp) {
        this.exp = exp;
        int level = getLevel();

        if(level==1 && exp>=1
                || level==2 && exp>=4
                || level==3 && exp>=7
                || level==4 && exp>=10
                || level==5 && exp>=15
                ){
            level++;

の23行目と26から39行目を

 public void setExp(int exp) {
        this.exp += exp;　　　　　　　　　
        int level = getLevel();

        if(level==1 && this.exp>=1　　　　
                || level==2 && this.exp>=4
                || level==3 && this.exp>=7
                || level==4 && this.exp>=10
                || level==5 && this.exp>=15
                ){
            level++;
に訂正

**Comment by Crocus7724** [comment]
修正ありがとうございました!!
